### ISSUE TITLE
Will there be an update to libsecp256k1?

### ISSUE THREAD

**Issue by gappleto97** [bitcoinxt/bitcoinxt#100]

**Comment by mikehearn** [comment]
Yes if/when we rebase onto 0.12 but it's not a priority. After initial sync this library makes little difference as your nodes signature cache should be warm, so block acceptance+relay involves very little signature checking, and tx relay time isn't much of a bottleneck right now.

**Comment by dgenr8** [comment]
Done in 0.11E.
