### ISSUE TITLE
Activity Monitor reports process in OS X as "Bitcoin-Qt"

### ISSUE THREAD

**Issue by TheAwer** [bitcoinxt/bitcoinxt#11]
Present in OS X with v0.10.1.0-7dd901c.

Shouldn't this be changed to be "Bitcoin-XT", or is there a reason for it being "Bitcoin-Qt"?

**Comment by mikehearn** [comment]
There were one or two places where renaming it seemed to cause other problems, I forgot why. But as you can't run both simultaneously anyway (unless you use separate ports and data directories) it didn't seem like a big deal at the time.

I can investigate some other time what it'd take to fiddle the remaining Bitcoin-Qt strings.

**Comment by mikehearn** [comment]
This will be fixed in the new release.
