### ISSUE TITLE
Enable pruning during node creation from latest check block

### ISSUE THREAD

**Issue by DeftNerd** [bitcoinxt/bitcoinxt#110]
When setting up a new BitcoinXT node, it's required to download all the blocks from the genesis block. Once everything is caught up, then you can restart your node with -prune=550 in order to prune the old blocks and allow the node to use less hard drive space. 

In order to allow BitcoinXT to be spread far-and-wide, we should allow new nodes to start with pruning from the first step by contacting several other nodes to determine the latest checkpoint block that's older than the minimum pruning age. Then we can start building the chain from that block. 

This will allow smaller VPS's to set up BitcoinXT nodes. 

Also, I'm unfamiliar with the reasoning for the 550 limit. Is it worth re-evaluating that number as the absolute number of minimum blocks?

**Comment by christophebiocca** [comment]
The problem is without a copy of UTXO, you can't "start" at a given block.

I believe you can just start the node with `-prune=550` the first time you run it, and that way it never keeps more than 550 blocks. It'll still use the same bandwidth, but will have bounded disk usage.
