### ISSUE TITLE
Create and test script to convert from Bitcoin Core to Bitcoin XT

### ISSUE THREAD

**Issue by DeftNerd** [bitcoinxt/bitcoinxt#111]
Since BitcoinXT and Bitcoin Core are so similar in operation until a big block fork, in theory the database schema should be compatible. 

I do not have a Bitcoin Core instance to test with, but it would be a good idea to test the following procedure

Stop bitcoind
Replace bitcoin binaries with bitcoinxt binaries
Restart daemon
Let BitcoinXT pick up where Bitcoin Core left off 

If this does work, it might be good to write a good script to accomplish this in an automated way that can be executed like

wget https://raw.githubusercontent.com/bitcoinxt/bitcoinxt/master/upgrade_from_core.sh | sh

or

wget https://bitcoinxt.software/upgrade | sh

If we make it so a single line can convert Bitcoin Core to Bitcoin XT in a few moments, we might see an increase of people switching implementations.

If there is support for this concept, I can put together the upgrade script and test it.

**Comment by dgenr8** [comment]
Is there a reason we don't / can't allow users the option to just install bitcoinxt onto an existing bitcoin installation?

**Comment by Conver** [comment]
I just tried this, and was able to. But it needed to reindex the whole blockchain everytime.

**Comment by dgenr8** [comment]
Outdated in specifics.  With the UTXO database update soon we'll be database compatible with the other cash implementations, aside from not supporting obfuscation.  Compatibility with the BTC chain will only be maintained while it's trivial to do so.
