### ISSUE TITLE
GUI unable to launch on Arch with Cinnamon

### ISSUE THREAD

**Issue by PartTimeLegend** [bitcoinxt/bitcoinxt#113]
On initial launch if you set the client to start with system then reboot no applet is visible. Launching from menu then tells you that a lock can not be established.

I fixed this temporarily using `top` and finding the PID and executing `kill XXX` and launching BitcoinXT manually from the menu and unselecting start with system.

I installed via `yaourt -S bitcoinxt-gui-git` from the AUR https://aur.archlinux.org/packages/bitcoinxt-gui-git/

**Comment by christophebiocca** [comment]
The only thing I can think of is that it starts up before the tray system is up, and fails to detect it properly.

Does this occur with the latest version of Core?

**Comment by PartTimeLegend** [comment]
Works fine with core, but I switched to XT as I support the need or the bigger blocks.
