### ISSUE TITLE
Update apt repo?

### ISSUE THREAD

**Issue by Nutomic** [bitcoinxt/bitcoinxt#128]
I'm installed XT from the [apt repo](https://bitcoinxt.software/apt.html). The latest available version is still v0.11.0D-b504e06.

Can you please update that to the latest version?

**Comment by mikehearn** [comment]
The apt repo is no longer maintained, sorry.

**Comment by Nutomic** [comment]
Too bad. I suggest you remove the link from the website then. Also, the download link still points to v0.11.D

**Comment by dgenr8** [comment]
Pinging @stevemyers just in case.

**Comment by stevemyers** [comment]
Hi sorry, just saw your ping.  I'll update the binary versions in the gitian-debian build.sh script and update the README.md file to point to the correct binaries also.  Look for a pull request coming soon.

**Comment by dagurval** [comment]
@Nutomic Can you try to do this and then apt-get update and apt-get upgrade? This repo is signed with the same key as the old one so there should be no warnings.

`
echo 'deb [ arch=amd64 ] http://xt.allnodes.xyz jessie main' > /etc/apt/sources.list.d/bitcoinxt.list
`

**Comment by Nutomic** [comment]
Works perfectly, thanks! Makes running a node so much easier :)
