### ISSUE TITLE
[apt] Move ntp to recommends

### ISSUE THREAD

**Issue by dagurval** [bitcoinxt/bitcoinxt#131]
Requested by [/u/RussianNeuroMancer)](https://www.reddit.com/r/bitcoinxt/comments/4704sd/aptrepository_has_been_updated_new_url/d0cxdha).

Currently the BitcoinXT apt package depends on installing ntp. Is there a good reason for this or can we make it optional (recommended)?

**Comment by RussianNeuroMancer** [comment]
If systemd-timesyncd is installed and running (timedatectl status) then as I understand synchronization can be configured via /etc/systemd/timesyncd.conf or via NTP= option in network interface description for networkd (again, if enabled and used).

My point is that there is other options for time synchronization besides ntpd.

**Comment by RussianNeuroMancer** [comment]
Seems like latest package still depend on ntp daemon.

**Comment by dgenr8** [comment]
@RussianNeuroMancer Are you able to submit a PR?

**Comment by RussianNeuroMancer** [comment]
I am not developer, I can't write fix for that.

**Comment by dagurval** [comment]
@RussianNeuroMancer Can you try out the .deb package in https://github.com/bitcoinxt/bitcoinxt/issues/154 (first comment)? Does it solve this issue?

**Comment by RussianNeuroMancer** [comment]
Yes, with this deb package ntp can be removed now. Thanks!

**Comment by RussianNeuroMancer** [comment]
Seems like deb package in repository was built with old build.sh, so this change doesn't included in Debian repository.

**Comment by dagurval** [comment]
There has not been a new release since the fix was merged.

It will be included in the next release.

**Comment by RussianNeuroMancer** [comment]
Ok, I see. Thanks for fast answer!

**Comment by dagurval** [comment]
Thank you for running XT :-)
