### ISSUE TITLE
Where is the 20mb consensus code?

### ISSUE THREAD

**Issue by erasmospunk** [bitcoinxt/bitcoinxt#14]
Sorry if it is obvious but I cannot find the code for the 20mb fork.

**Comment by marzig76** [comment]
Right in the readme, it says, "Please note that Bitcoin XT does not currently change anything about block size limits, although a future version might."

**Comment by mikehearn** [comment]
Gavin hasn't submitted any patches to XT to change the block size limit yet. When/if he does submit, the release notes will record the fact that the new version votes for a new block size limit.

**Comment by rubensayshi** [comment]
@mikehearn why did you `git commit --amend` instead of adding that line in a seperate commit ... :/ ?

**Comment by mikehearn** [comment]
The README explains:



The patch set is a set of commits on top of each branch, with the patches
being rebased on the master branch when time permits and rebased on top of
the release branches when a new upstream release is made. Therefore XT does
not have its own release cycle.

*Patches, or changes to patches, are handled with rebases*. Therefore we
force push over previous pushes. Don't fork from the Bitcoin XT repository
unless you're able to handle that

**Comment by erasmospunk** [comment]
Thanks for the heads up. I was under the impression that there was a branch with the new consensus code.
