### ISSUE TITLE
Does Bitcoin-XT support a solo mining option?

### ISSUE THREAD

**Issue by jeong760** [bitcoinxt/bitcoinxt#141]
Dears,

Just I wonder if Bitcoin-XT supoort a solo mining option. because Yesterday I was installed it on my computer in order to test and I found when after Installed it cound not possible connect a local wallet with cgminer and mfgminer for solomining configuration on bitcoin.conf file.

**Comment by dgenr8** [comment]
@jeong760 Can you provide any details / logs to document what you are seeing?

**Comment by dgenr8** [comment]
No answer, closing.
