### ISSUE TITLE
Clarify policy on consensus deviation from Bitcoin-Core.

### ISSUE THREAD

**Issue by nathan-at-least** [bitcoinxt/bitcoinxt#15]
When I first read about this project some time ago the synopsis I was left with was along the lines of "Bitcoin-XT improves networking and other implementation aspects of Bitcoin while being consensus compatible." So I imagined, maybe there's an "XT backbone" that core nodes can't understand, but the blocks flowing between that network and the mainstream network were all part of *the* blockchain.

In recent discussions around block size, it sounds like the max blocksize may be increased in Bitcoin-XT. I believe this would deviate from consensus in the mainnet, and introduce a hard fork if deployed.

Could we add some documentation near the top of the README about Xt's consensus policy?

Am I mistaken in that Xt doesn't actually ever connect to the production network?

Are consensus deviating changes only on development or test branches and/or a test net?

**Comment by mikehearn** [comment]
XT is the same thing as Core with a few extra patches. So yes it connects to the P2P network.

The README already states that XT does not currently change anything in the consensus rules. If it does in a future version, the README will be updated to reflect that.
