### ISSUE TITLE
How can we stay tunned about XT?

### ISSUE THREAD

**Issue by disposable-ksa98** [bitcoinxt/bitcoinxt#17]
Theymos and his hounds seem to be doing some censoring at /r/Bitcoin. I saw a very detailed post that only enumerated facts about the debate (eg: it included some quotes from Satoshi, facts about Gavin, Mike, Blockstream, etc) but then it was gone.

So I'm afraid that when the time comes, you won't be able to inform the users since Theymos controls r/Bitcoin, bitcointalk.org, bitcoin.org, and bitcoin.it. Any ideas?

By the way I read part of the debate in the mailing list and I want to thank you for what you are doing. It must be stressful to discuss all day with people who claim to want the same as you, but in the end are just filibusters (by stopping all progress they win by default).

If you get big companies and miners on board you should be fine. Imagine if Coinbase and similar companies coordinated to send an email to inform their users about the upgrade. Users who run full nodes would get the memo for sure one way or another.

**Comment by chriswheeler** [comment]
Discussion: https://groups.google.com/forum/#!forum/bitcoin-xt
Announcements: https://groups.google.com/forum/#!forum/bitcoin-xt-announce

**Comment by mikehearn** [comment]
Once XT has a website you will be able to sign up for email announcements there. I agree that it's annoying that theymos has decided to try and interfere with people learning about XT, but we'll see how it goes.

**Comment by anton000** [comment]
are there updates on the XT site @mikehearn ?

**Comment by bcolb** [comment]
In regards to the moderation or /r/bitcoin, there is also a new subreddit dedicated to XT, [/r/bitcoinxt](https://www.reddit.com/r/bitcoinxt/) if Reddit is your preferred avenue to stay up on things.

**Comment by essofluffy** [comment]
voat.co/v/bitcoin

**Comment by mikehearn** [comment]
The new website is live. There's a box where you can subscribe to the announcements list.
