### ISSUE TITLE
Might want to remove the download from github link

### ISSUE THREAD

**Issue by rromanchuk** [bitcoinxt/bitcoinxt#26]
Now that you have a domain...i didn't realize latest binaries were already built.

**Comment by mikehearn** [comment]
They aren't formally launched yet. Until they are, the defaults are still for 0.10.2A

I realise the wait is frustrating, but please bear with us. We'll make sure everyone knows once 0.11A is released.

**Comment by rromanchuk** [comment]
thanks, @mikehearn dumb question, is 0.11A the release watered from 0.11.0 of core? If my node is already on 0.11.0 core should i wait for .11A? From what i remember of the release notes there were some backward compatibility concerns with this release. (I don't want to reindex)

**Comment by mikehearn** [comment]
Yes, 0.11A is indeed based on Core 0.11
