### ISSUE TITLE
Arch linux release has no GUI and bitcoind exits with Exec format error

### ISSUE THREAD

**Issue by 1Hyena** [bitcoinxt/bitcoinxt#260]
I'm upgrading to Bitcoin Cash and I had to choose between all those full node wallets. The reason why I chose BitcoinXT was because it was the only wallet that had arch linux binaries ready (I just switched from Linux Mint to Arch Linux). Also BitcoinXT defaults to Bitcoin Cash fork, other dev teams have a separate release for Cash. So that's why I chose XT and wanted to thank you guys for making it easy for me to choose ;)

However, when I downloaded the bitcoin-xt-0.11.0-G-aarch64-linux-gnu.tar.gz release then it turns out it does not have the GUI included. Also when I tried to run the bitcoind binary I received an error:
```
[hyena@Courage bin]$ ./bitcoind --help
bash: ./bitcoind: cannot execute binary file: Exec format error
```

**Comment by dgenr8** [comment]
Can you recommend a quick way to create an environment to reproduce the error you are getting?

If we aren't able to fix this soon, we'll probably remove the build. It would be great if anyone would like to help.

**Comment by 1Hyena** [comment]
Interestingly the normal linux 64bit build worked well on my arch (manjaro linux to be exact but it is essentially still arch) :D . I have to admit that I haven't used arch linux before so I am just learning it. so the only way I could recommend a way to reproduce the error is to boot a [manjaro linux cinnamon build](https://sourceforge.net/projects/manjarolinux-community/files/cinnamon/17.0.2/) from USB, then download the given bitcoinXT binary and attempt to run `bitcoind`. However, since the generic Linux build runs very well under my system I am also wondering whether arch build is necessary after all.

**Comment by 1Hyena** [comment]
woops, my bad :D turns out aarch64 is for ARM processors:
https://archlinuxarm.org/platforms/armv8/generic

so I accidentally thought it was for regular arch linux. sorry for creating confusion
