### ISSUE TITLE
Ubuntu 14.04. installation issue: error processing the archive

### ISSUE THREAD

**Issue by davalb** [bitcoinxt/bitcoinxt#27]
I currently have BitcoinQT installed and I get an error when I try to install BitcoinXT with apt-get on Ubuntu 14.04. Should I remove BitcoinQT first? (I am afraid to lose the already downloaded blockchain if I do that.) This is the error message:
```
dpkg: error processing the archive /var/cache/apt/archives/bitcoinxt_0.11A_amd64.deb (--unpack):
  Attempt to "/ usr / bin / bitcoin-qt" to overwrite that bitcoin-qt is also in package 0.11.0-trusty1
dpkg-deb: error: Insert sub-process was (interrupted data transfer (broken pipe)) by signal killed
Errors were encountered while processing:
  /var/cache/apt/archives/bitcoinxt_0.11A_amd64.deb
E: Sub-process / usr / bin / dpkg returned on error code (1)
```

**Comment by mikehearn** [comment]
You should be able to uninstall the existing package without losing any data. But if you're worried, just rename your ~/.bitcoin directory during the uninstall - that way in the unlikely event that your package deletes the block chain data if you uninstall it, nothing will happen.

**Comment by davalb** [comment]
Thanks, that worked flawlessly. I removed QT, installed XT and blockchain and wallet data are still there.
