### ISSUE TITLE
Cash hard fork Nov 13

### ISSUE THREAD

**Issue by dgenr8** [bitcoinxt/bitcoinxt#271]
New DAA
Enforce NULLDUMMY
Enforce LOW_S

**Comment by andyrowe** [comment]
Is XT going to merge this DAA?  Folks are asking in r/bitcoinxt and I figure I'd update them.

**Comment by phillipsjk** [comment]
In any case, this may be an opportunity for me to set up a Bitcoin Cash fork monitor like this one:

https://www.btcforkmonitor.info/

I still have not finished the IRL stuff that prevented my fork monitor from being ready in August though.

**Comment by dgenr8** [comment]
XT will be able to follow consensus changes to the cash network at the time they go into effect.

**Comment by 1Hyena** [comment]
@dgenr8 hopefully we'll see a new version published soon then

**Comment by dgenr8** [comment]
Closing, the November 2017 cash hard fork is implemented #277.  Release H will support the fork and be published as soon as possible.
