### ISSUE TITLE
Not installing properly from apt repository

### ISSUE THREAD

**Issue by gappleto97** [bitcoinxt/bitcoinxt#28]
Error message as follows:

    Unpacking bitcoinxt (0.11A) ...
    dpkg: error processing archive /var/cache/apt/archives/bitcoinxt_0.11A_amd64.deb (--unpack):
     trying to overwrite '/usr/bin/bitcoin-qt', which is also in package bitcoin-qt 0.11.0-trusty1
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    Errors were encountered while processing:
     /var/cache/apt/archives/bitcoinxt_0.11A_amd64.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by christophebiocca** [comment]
Looks like you've got bitcoin-qt installed, and it's conflicting? You'll probably need to uninstall it first.

Sounds like the `.deb` package should have a [Breaks or Conflicts](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-breaks) annotation on it, to avoid the cryptic error message.

**Comment by mikehearn** [comment]
We should just rename the bitcoin-qt binary in the DEB. There's a script in git master that does the DEB builds. If someone could take it over and do it properly, that'd be perfect.

**Comment by abelgo** [comment]
Hi guys,  I'm a bit confused here. 

Is there an apt-get bitcoinxt package ? 

https://github.com/bitcoinxt/bitcoinxt/blob/master/doc/build-unix.md seems to be taken straight out of the old core and point to that ?

If so are there any novice instructions on how to add the required sources.list files and do the xt update ?

**Comment by christophebiocca** [comment]
@abelgo: Wrong place. Go look at https://bitcoinxt.software/apt.html for installation instructions.

**Comment by abelgo** [comment]
Ok  https://bitcoinxt.software/apt.html mostly got me what I needed.

One other down side was no bitcoin-cli binary so I had to install the orignal bitcoind package first to get it then disable it. 

This is my cheet sheet it might help some one.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

_//assumes apt-get install bitcoind_
_// you need your own initd to start it up on boot._
_// use the bitcoind one._

cd /etc/init
sudo stop bitcoind
sudo cp ./bitcoind.conf ./bitcoinxt.conf

_ //This is my one you might have set it up differently_

description "bitcoinxt"

start on filesystem
stop on runlevel [!2345]
oom score 900
nice 10
kill timeout 25
expect daemon
respawn
respawn limit 10 60 # 10 times in 60 seconds

script
user=bitcoin
home=/data/bitcoin
cmd=/usr/bin/bitcoinxt
pidfile=$home/bitcoinxt.pid

[[ -e $pidfile && ! -d "/proc/$(cat $pidfile)" ]] && rm $pidfile
[[ -e $pidfile && "$(cat /proc/$(cat $pidfile)/cmdline)" != $cmd* ]] && rm $pidfile
exec start-stop-daemon --start -c $user --chdir $home --pidfile $pidfile --startas $cmd -b --nicelevel 15 -m
end script

_// disable the old bitcoind from starting in the future_

echo manual | sudo tee /etc/init/bitcoind.override
sudo start bitcoinxt

_//OK ?_

bitcoin-cli getinfo

_//looks something like this  XT ??_

{
    "version" : 110000,
    "protocolversion" : 70010,
    "walletversion" : 60000,
   .......

**Comment by schildbach** [comment]
The CLI-tool is called "bitcoinxt-cli".

**Comment by mikehearn** [comment]
Yeah, it's meant to be parallel installable with the Bitcoin Core package, but it seems some debians bundle Qt and bitcoind together so in fact it isn't always so. The Debian package needs work, volunteers wanted.
