### ISSUE TITLE
75% consensus too risky?

### ISSUE THREAD

**Issue by MatthewLM** [bitcoinxt/bitcoinxt#29]
Hello,

It's a good idea to put the hard fork to a vote, but why was 75% chosen? It may appear to be a high majority, but 25% of miners disagreeing could mean a significant opposition. Even though they would be a minority, couldn't they still cause a vocal opposition? Maybe a significant number of people would maintain a legacy chain and perhaps brand it as the "True Bitcoin". It's not only miners but a hard fork needs users to be OK with it as well, though I would assume most people would just go along with it without any concern.

I'm not saying 75% is a bad idea, but I'd like to know what reasoning has gone behind that number, and if there have been other considerations about non-miner user consensus.

I do agree though that the blocksize should be increased.

Matthew

**Comment by christophebiocca** [comment]
Miners don't *have* to mine larger blocks as soon as they're *allowed* to.

What that means is it's very likely that the 75% threshold + 2 week waiting period will come and go long before we see any miner try to cross the magic threshold. It could be weeks, months. It probably won't happen until we've got blocks that approach the 1MB threshold on a regular basis. Miners have no incentive to make a big block until they're getting paid for it.

**Comment by MatthewLM** [comment]
@christophebiocca Sure, but there is nothing stopping them. The first 1+MB block could come whenever. After that moment the blockchains would fork for real, and there's no know what level of opposition there would be. Would it hurt to increase the consensus percentage?

**Comment by mikehearn** [comment]
Gavin chose it, but which threshold would you have chosen?

It's probably just splitting the difference between 50% and 100%. 50% is technically the most like democracy, but also risks bad behaviour if the actual 'vote' was too close to that. 100% is obviously a non-starter, it'd allow anyone to hold the entire community to ransom by just mining a few blocks and saying "pay me to stop mining". 75% is somewhere in the middle.

**Comment by MatthewLM** [comment]
@mikehearn OK, and to extend the last point, some mining pools have a high percentage of the network, so increasing the percentage much further could make it easy for them to have a very strong influence, so maybe 75% is about right considering that.

Though what I would have personally done is to have Bitcoin XT mark transactions and measure a vote by Bitcoin days destroyed. Miners are important, but the users that own and trade bitcoin are also important. By looking at a measure of coins*age in transactions it is possible to measure the support of these users. I do think coin ownership in conjunction with mining should at least be considered in the future as a method to vote for protocol changes such as these.

**Comment by mikehearn** [comment]
I think someone would have to prototype an implementation of that first. It would require all users to upgrade their wallets, amongst other issues. Lots of very interesting open research questions around the topic of user voting.

Also be aware that some people e.g. the admins of bitcoin.org believe that user voting is some kind of evil that should never happen. They said they'd remove mention of any wallet that didn't follow miner consensus. Some wallets rely quite heavily on traffic from that site, so that issue would need to be tackled first. For now a miner based voting mechanism is a good start. We can always decide what to do later, if there's some kind of split between the user community and the miner community.
