### ISSUE TITLE
Tags/commits aren't PGP signed

### ISSUE THREAD

**Issue by petertodd** [bitcoinxt/bitcoinxt#3]
Should be following best-practice used by parent Bitcoin Core project.

**Comment by TheAwer** [comment]
Any progress on this, @mikehearn?  I wanted to install Bitcoin XT, but without a .sig for the OS X download (and without knowledge or instructions on how to build it myself), I am reluctant to install what is on the .dmg.

**Comment by mikehearn** [comment]
It's pointless to use a PGP signature for these downloads. They are served over SSL and you don't have a path to my PGP key through the web of trust anyway so you'd have to download it ... over SSL.

**Comment by TheAwer** [comment]
I suppose this is fine for now, but if Bitcoin XT becomes a more common client (which could happen with all the talk about 20 mb blocks), you should really look into this.  

And a SSL connection doesn't prevent all threats - a PGP signature would just be another layer of optional security (of debatable security), which couldn't hurt.  Bitcoin Core downloads on the https Bitcoin.org website has a SHA256SUMS.asc to verify downloads - perhaps you could at least add SHA checksums for the downloads?

**Comment by mikehearn** [comment]
If we do the block size change, then I guess I'll team up with Gavin and he can sign things. His key is likely more widespread and trusted than mine.

Sure, I'll look at adding SHA256 sums to the next release.

**Comment by TheAwer** [comment]
@mikehearn, you could look into https://keybase.io to build trust in your key using your online accounts without getting into the web of trust.

If you sign up in the next few hours, the code "shit-yeah-facebook" will get you an account right away.  Otherwise you have to get an invite (it's still in alpha) or wait in the queue.

**Comment by mikehearn** [comment]
I could link my PGP key with github, but it'd boil down to an almost exact equivalence - it just makes github into a CA.

**Comment by TheAwer** [comment]
If you do decide to sign up for Keybase, you can also verify from other accounts (Reddit, Twitter, Coinbase, your website, etc.).  And as the message is PGP signed on all those sites, those websites are more of an intermediary for verifying your identity than a CA.  

SHA256 sums sounds good for the next release.

**Comment by jwilkins** [comment]
@mikehearn step away from the keyboard....

**Comment by mikehearn** [comment]
@TheAwer there are SHA256 hashes of the downloads in the gitian release files:

https://github.com/bitcoinxt/gitian.sigs/blob/master/0.10.2A-linux/mike%40plan99.net/bitcoin-linux-0.10-build.assert

and that file is signed with my PGP key which you can get here:

https://vinumeris.com/mike-hearn.asc

Is that sufficient?

**Comment by TheAwer** [comment]
Yeah, that looks like an okay setup, @mikehearn (although it could certainly be more streamlined - like one file with all the hashes in it.  This should be enough for those who want to check, though.).  Only problem is that I can't find the hash of Bitcoin.XT.dmg.  It seems that you skipped this file for some reason or something?  The closest match would be the hash of bitcoin-osx-signed.dmg, but I'm not sure where that file is from.  From a quick check it appears that you do have the hashes of the rest of the files.

Did I miss this somehow?

**Comment by mikehearn** [comment]
Bitcoin.XT.dmg is that file renamed. I think the hashes should match unless the Finder twiddles stuff inside the DMG when renaming it.

Like I said, checking PGP signatures on these things doesn't tell you much, as the root of trust is still the PKI anyway, and the binaries on Win/Mac are signed as well. So I don't want to spend time on streamlining this right now. Data from bitcoin.org logs shows that ~nobody verifies PGP signatures. It's tantamount to security theatre.

**Comment by TheAwer** [comment]
My bad, I didn't actually check the hashes to see if it was the same.  It is.  Thanks for doing this - having this system is still better than nothing.  And I think that it's important to have security features like PGP sigs for those users who care enough to check this (I am one of those who check the PGP signatures).

**Comment by sesam** [comment]
Bitcoin is either business or show business. In both cases security theatre has value. And it keeps devs honest and is a path towards safer binary distribution. Doesn't have to be perfect from the beginning. OTOH, users should compile it themselves.

**Comment by mikehearn** [comment]
There are GPG signed gitian reports that you can compare against the downloads.
