### ISSUE TITLE
Log filled with INVALID MESSAGESTART

### ISSUE THREAD

**Issue by mogray5** [bitcoinxt/bitcoinxt#339]
Hi I have version 0.11.0-H running for Bitcoin Cash and my logs are filled with message like below.   I'm running the client on a Debian machine.  Any help is appreciated.  Thanks. 

2018-02-17 20:19:34 PROCESSMESSAGE: INVALID MESSAGESTART version peer=1744977

**Comment by dagurval** [comment]
We plan to fix this, see issue https://github.com/bitcoinxt/bitcoinxt/issues/310

For now you can ignore it, or remove this line and re-compile XT https://github.com/bitcoinxt/bitcoinxt/blob/68511ffd259960fa21953f4ced13ea26d9703661/src/main.cpp#L5839

**Comment by mogray5** [comment]
Ok thanks.  My node wasn't showing up on https://cash.coin.dance/nodes so I was thinking it was down due to this error but appears coin.dance had an issue of their own causing it not to be counted.

**Comment by dgenr8** [comment]
@mogray5 Ok to close?

**Comment by mogray5** [comment]
Ok with me.
