### ISSUE TITLE
Startup info box image pixelation

### ISSUE THREAD

**Issue by TheAwer** [bitcoinxt/bitcoinxt#37]
OS: OS X 10.10.4
XT: v0.11.0.0-2b918be

The XT logo image in the startup page (with "Activating best chain...", etc.) is rather pixelated.  

You can also faintly see the square outline of the background of the logo image.

These obviously aren't very high priority issues, but it would be one very easy way to enhance the software.  It would also make a better first impression of the app.

**Comment by mikehearn** [comment]
What sort of screen do you have? I have a MBP Retina and I don't see any visual artifacts on the splash screen.

**Comment by jonasschnelli** [comment]
@TheAwer is right. The splash screen is non HiDPI (see below).
You probably need to exchange https://raw.githubusercontent.com/bitcoinxt/bitcoinxt/master/src/qt/res/icons/bitcoin.png to suport 1024x1024

<img width="592" alt="bildschirmfoto 2015-08-18 um 08 45 01" src="https://cloud.githubusercontent.com/assets/178464/9324056/0423f82c-4587-11e5-8f1b-c2e1dec5a257.png">

**Comment by mikehearn** [comment]
Hmm. OK. I'll take a look when I have a bit of time next week. I didn't notice any issues, but perhaps my eyesight is getting worse again .... :/

**Comment by TheAwer** [comment]
@mikehearn if it helps, I'm on an older MacBook Pro (non-Retina).  I can see the background artifacts easier by looking at the screen from a low angle.  Look for the slightly darker stripe in the background - just above the middle of "Loading" in the the picture jonasschnelli posted.

**Comment by mikehearn** [comment]
Fixed by 9a448608941944ae1cb70eb6ecea9e22254e2656
