### ISSUE TITLE
ERROR: ReadBlockFromDisk : Deserialize or I/O error - ReadCompactSize() : size too large

### ISSUE THREAD

**Issue by MineForeman** [bitcoinxt/bitcoinxt#4]
It is almost certainly an upstream issue and has been (posted here)[https://github.com/bitcoin/bitcoin/issues/5668] but I will post a note here, close it and then tell them about it as well.

It is annoying because my lighthouse server went out of sync twice now.  (not for long, still annoying though, I need to setup daemontools)

**Comment by rromanchuk** [comment]
hey @MineForeman, i was one of the nodes that ran into the above issue while back. Did you do anything out of the ordinary when switching form what i assume was 0.11.0 core to 11A? Are you using EBS as your media?
