### ISSUE TITLE
Switch to disable tor group download and anti-dos scheduling

### ISSUE THREAD

**Issue by Polve** [bitcoinxt/bitcoinxt#40]
As outlined in this comment:
http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-August/010379.html
the automatic download of tor exit nodes has serious privacy concerns, and should be disabled by default.

Is it possible to completely disable the use of anti-DoS resource scheduling via a commandline switch or configuration setting?

The complete text of the original comment follows:
> Bitcoin XT contains an unmentioned addition which periodically downloads
> lists of Tor IP addresses for blacklisting, this has considerable privacy
> implications for hapless users which are being prompted to use the
> software.  The feature is not clearly described, is enabled by default, and
> has a switch name which intentionally downplays what it is doing
> (disableipprio).  Furthermore these claimed anti-DoS measures are trivially
> bypassed and so offer absolutely no protection whatsoever.
>
> Connections are made over clearnet even when using a proxy or onlynet=tor,
> which leaks connections on the P2P network with the real location of the
> node.  Knowledge of this traffic along with uptime metrics from
> bitnodes.io can allow observers to easily correlate the location and
> identity of persons running Bitcoin nodes.  Denial of service can also be
> used to crash and force a restart of an interesting node, which will cause
> them to make a new request to the blacklist endpoint via the clearnet on
> relaunch at the same time their P2P connections are made through a proxy.
> Requests to the blacklisting URL also use a custom Bitcoin XT user agent
> which makes users distinct from other internet traffic if you have access
> to the endpoints logs.

**Comment by paoloaga** [comment]
+1 !!!!

**Comment by zander** [comment]
Duplicate of issue 38

**Comment by christophebiocca** [comment]
As explained in #38, this won't run if you explicitly set a proxy or `listen=0`.

There is also `-disableipprio` which also disables that code regardless of any other settings.

**Comment by Polve** [comment]
But I don't want to disable listening, quite the contrary, so listen=0 is out of question for me.
Also, if the claim here is correct: http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-August/010386.html that option is not enough.

Does -disableipprio disable the download or has the same problem?

**Comment by christophebiocca** [comment]
> Does -disableipprio disable the download or has the same problem?

[Look at the code](https://github.com/bitcoinxt/bitcoinxt/commit/73c9efe74c5cc8faea9c2b2c785a2f5b68aa4c23#diff-11780fa178b655146cb414161c635219R263) and come to your own conclusion. I'm pretty sure it does, but I don't want to mislead.

> But I don't want to disable listening, quite the contrary, so listen=0 is out of question for me.
> Also, if the claim here is correct: http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-August/010386.html that option is not enough.

What's your setup? Are you operating in both cleartext and Tor?

If yes, you probably have no privacy against any semi-serious attacker (they can deanonymize by sending you new transactions on either end).

If you're only on tor, the email you linked to says running `onlynet=tor` is safe (I think):

>The code does disable downloading of the Tor exit node list if fListen
> is false, or if there is a proxy setup, this means the statement:

>>  Connections are made over clearnet even when using a proxy or
>> onlynet=tor,

> is false.

**Comment by Polve** [comment]
> What's your setup? Are you operating in both cleartext and Tor?
I simply want to run a (public) node that serves also tor exit nodes (but I'not running tor myself).

-disableipprio indeed seems to do the trick, then that's fine for me, if there are not other unexpected behaviours when using that option.

In that case feel free to close this issue, but I think that due to privacy concerns that should be the default value, or at least (much) better documented.

**Comment by mikehearn** [comment]
The post to the Bitcoin Core list is (surprise) both manipulatively written, and wrong. I expect much more of this kind of thing from that camp unfortunately, given recent history.

> Bitcoin XT contains an unmentioned addition

It's mentioned on the website (click patches), in the commit logs, in the release announcement and has been discussed frequently on the mailing list.

> periodically downloads lists of Tor IP addresses for blacklisting

Tor is not "blacklisted", traffic from it is treated as being less important than non-Tor traffic in case of resource exhaustion. Which should not happen unless there's a DoS attack   (DoS attacks targeting XT specifically have occurred multiple times, hence this patch).

> this has considerable privacy implications for hapless users which are being prompted to use the software

It has no privacy implications. Nodes will attempt to find their own IP address, open up NATs via UPnP and generally do the best they can to become visible to the whole internet. Anyone who wants to find IPs of Bitcoin Core or XT users can, if the software is working properly and they aren't specifically configured to use a proxy.

> Connections are made over clearnet even when using a proxy or onlynet=tor

This is wrong. As the premise of this paragraph is incorrect, so is the rest of it which describes the "implications".

The -disableipprio flag does disable the download, but I don't recommend it. Knee jerk reactions are bad: Tor is being used to attack nodes, so switching off some defences wouldn't be smart.
