### ISSUE TITLE
BIP64

### ISSUE THREAD

**Issue by shravan-shandilya** [bitcoinxt/bitcoinxt#416]
Hi Team,
I learned from the BitcoinXT website that, it supports 'getutxos' (BIP64). How do I use it?
Is there a RPC call for this particular feature? If yes, its not part of the Ubuntu PPA build.
Can you please provide instructions to enable this?

**Comment by dagurval** [comment]
Hi, 

BIP64 is in the network protocol only, so you’d have to connect to bitcoind as a node to use the call. 

However, the RPC function ‘gettxout’ returns the same info. Did you see that function?

**Comment by shravan-shandilya** [comment]
Thanks @dagurval 
As I understand 'gettxout' gives the detail of a particular UTXO given the Transaction ID and output Index. 
I was looking to list all the available UTXOs for a given address.
