### ISSUE TITLE
README.md doesn't mention ip prioritization changes

### ISSUE THREAD

**Issue by chriswheeler** [bitcoinxt/bitcoinxt#43]
> Currently it contains the following additional changes:

I think the text from https://bitcoinxt.software/patches.html regarding Anti-DOS patches would suffice.

**Comment by mikehearn** [comment]
We should just change the README to point to the website now. It used to function as an ad hoc website but that's no longer necessary.

**Comment by rromanchuk** [comment]
You might want to explicitly add the flag for disabling in that text as well. So much nonsense going around, might want to err on the side of being overly explicit.

**Comment by mikehearn** [comment]
The README points to the website which has a patches page that discusses it.
