### ISSUE TITLE
BitCoin-XT Mac version just used the bundle identifier from the official bitcoin client

### ISSUE THREAD

**Issue by core-code** [bitcoinxt/bitcoinxt#437]
please change the
CFBundleIdentifier
in 
share/qt/Info.plist.in

from 
org.bitcoinfoundation.Bitcoin-Qt
to something else

each Mac app has to have a unique bundle ID, so stealing the bundle ID from some other project is a super bad idea

**Comment by dgenr8** [comment]
Thank you @core-code.  Ping @kyuupichan @jeffgran
