### ISSUE TITLE
Stealth mode broken on BCH

### ISSUE THREAD

**Issue by dagurval** [bitcoinxt/bitcoinxt#443]
The stealth mode (`-stealth-mode=1`) which was introduced during the XT targeted DDoS attacks in 2015 makes XT masquerade as an older version of Bitcoin Core. 

This obviously won't fool anyone on the Bitcoin Cash network. Suggest we either make XT masquerade as a different BCH client or completely remove this feature.

**Comment by dgenr8** [comment]
I vote for removal.
