### ISSUE TITLE
sighashlimit and accuratesigoplimit reported as max unsigned 64-bit integer

### ISSUE THREAD

**Issue by Matoking** [bitcoinxt/bitcoinxt#45]
My BitcoinXT node running on an ODROID-XU4 (an ARM development board) reports the sighashlimit and accuratesigoplimit values in getblocktemplate as the maximum unsigned 64-bit integer (18446744073709551615).

Since many JSON parsers (eg. jansson used by cgminer) fail to parse the response due to the extremely large integer, this also has the side effect of breaking some applications which depend on being able to parse the JSON response returned by getblocktemplate.

**Comment by mikehearn** [comment]
Ah, JSON. What a wonderful data format ....

This is something for @gavinandresen to look at. Sounds like it could be hurting miner adoption.

**Comment by Matoking** [comment]
From what I've gathered (eg. Google's API [here](https://developers.google.com/discovery/v1/type-format)), the best way would be to encode it as a string when its value exceeds 9007199254740991 (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)), as it is the maximum safe integer that can be represented in Javascript, and thus, JSON.

**Comment by dgenr8** [comment]
Since the meaning of max numbers is "effectively no limit", these keys could be omitted entirely when value == max.

**Comment by gavinandresen** [comment]
RE: encoding as string or leaving it out if it is max: RPC values should always be there AND always be a single type. Otherwise the code that interprets RPC results becomes a mess of conditionals.

2^53 is as good a value for "no limit" as 2^64 in this case, so lets go for the simple fix: define a uint64_t JSON_NUMBER_LIMIT = (1L<<53)-1; and use that.

**Comment by mikehearn** [comment]
@Matoking would you be willing to try this patch and let us know if it fixes things?

https://github.com/bitcoinxt/bitcoinxt/pull/49
 
That'd help a lot!

**Comment by Matoking** [comment]
The patch seems to work now that the JSON number limit is defined as a constant instead of as a result of a bit shift. cgminer also connects to the node with no problems with the fix in place.

**Comment by luke-jr** [comment]
@gavinandresen This should be added to BIP 101 please.

**Comment by Matoking** [comment]
Fixed by patch #49
