### ISSUE TITLE
bitcoinxt broadcasts my ipv6 address when running with tor

### ISSUE THREAD

**Issue by lunokhod** [bitcoinxt/bitcoinxt#47]
I am running bitcoinxt through a tor proxy on osx, but I have just noticed that even though my ipv4 address is hidden by tor, that there is a client connected to my real ipv6 address.

For info, I am running osx 10.10.5, tor  0.2.6.10, bitcoinxt v0.11.0.0-30017c1, and I have the following in my bitcoin.conf file:

~~~~
proxy=127.0.0.1:9050
onion=127.0.0.1:9050
listen=1
discover=1
~~~~

**Comment by mikehearn** [comment]
XT doesn't change anything in that part of the code: it will behave the same way as Core. So I guess this issue exists upstream too.

I think the problem is you're forcing listen=1. Normally using Tor would disable listening.

**Comment by lunokhod** [comment]
Actually, the solution appears to be to set discover=0 (listen=1 allows me to run a hidden service). My bad.

I think that it is odd that I need to do this, as discover=1 only revealed my ipv6 address and not my ipv4 address. In any case, I'm going to close this issue, and will bring it up at bitcoin core if anything odd resurfaces.

**Comment by mikehearn** [comment]
Well it seems like something that should be fixed: such misconfigurations should be detected.

If you submit a patch to XT we'll review it and merge it, but you should indeed submit any fix to Core as well.

**Comment by dagurval** [comment]
I took a look at this -- and it does seem to be an valid, documented configuration.

From doc/tor.md:
> When -externalip is specified, no attempt is made to discover local
> IPv4 or IPv6 addresses. **If you want to run a dual stack, reachable
> from both Tor and IPv4 (or IPv6), you'll need to** *either pass your
> other addresses using -externalip, or* **explicitly enable -discover**.
> Note that both addresses of a dual-stack system may be easily
> linkable using traffic analysis.
