### ISSUE TITLE
Implement Bandwidth Limit Settings

### ISSUE THREAD

**Issue by wladston** [bitcoinxt/bitcoinxt#53]
There should be a GUI setting to control how much bandwidth the node is allowed to use, as discussed in this issue: https://github.com/bitcoin/bitcoin/issues/273

I'm willing to implement this issue, but that would be my first Bitcoin contribution. I would require some tutoring over IRC, but I can definitively implement this, if no one else wants to.

**Comment by zander** [comment]
that would be wonderful

**Comment by mikehearn** [comment]
Absolutely happy to do patch review and guidance. I'm usually on IRC during the European afternoon. Or you can just post questions to the mailing list.

**Comment by mikehearn** [comment]
@jonasschnelli has already made a start on this. You could take a look at his code here, as a first step:

https://github.com/bitcoin/bitcoin/pull/6589

**Comment by jonasschnelli** [comment]
limiting the bandwidth over all network operations is IMO a bad practice. A bandwidth trottle should respect important things like relay of blocks/tx or even responding to merkleblocks (maybe configurable). IMO most bandwidth could be kept tight if serving historical blocks would have a cap (or a throttle limit).

**Comment by mikehearn** [comment]
In practice steady state bandwidth is trivial. The issue people complain about it almost certainly historical block chain upload. It's fine to focus on that only for now.

**Comment by dgenr8** [comment]
Done in 0.11D.
