### ISSUE TITLE
0.10 Final Mac DMG is corrupt

### ISSUE THREAD

**Issue by risenhoover** [bitcoinxt/bitcoinxt#6]
I tried to download and install the 0.10 Final DMG but upon unpacking and attempting to run, OSX reports it is corrupt. The RC version runs without error.

**Comment by mikehearn** [comment]
OK. That's a Gatekeeper error, I must have messed up the gitian-specific signing process (it's kind of fiddly). 

0.10.1 is about to come out any day now so I don't want to spend time fixing the OS X package for 0.10 Final, only to see it be immediately obsoleted. If the RC works please stick with that and I'll make sure to test the next build I do better to ensure the signatures are correct. Thanks!

**Comment by mikehearn** [comment]
I've released 0.10.1 - does that work better for you?
