### ISSUE TITLE
0.11B -stealth-mode is not mentioned in command line usage

### ISSUE THREAD

**Issue by Beanow** [bitcoinxt/bitcoinxt#62]
`bitcoinxt-qt -? | grep stealth` is blank.

It does work though, connecting to a 0.11A node using `-stealth-mode` makes it report.

```
receive version message: /Satoshi:0.11.0/: version 70002, blocks=222611, us=0.0.0.0:0, peerid=2959
```

**Comment by jlopp** [comment]
Added documentation in https://github.com/bitcoinxt/bitcoinxt/pull/85
