### ISSUE TITLE
Rate limit the popup warnings?

### ISSUE THREAD

**Issue by Beanow** [bitcoinxt/bitcoinxt#63]
This happened when I tried to send a transaction with one of the publicized private keys.
![Warning spam](http://ss.oscp.info/2015-09-10_05-09-55.png)

**Comment by dgenr8** [comment]
Ah that's lovely. Can you add a few specifics?

**Comment by Beanow** [comment]
Besides the UI thread being bricked completely for about 20 seconds at a time?
The wallet hadn't caught up with the mempool, so it thought inputs were still available, I made TXes from the Send tab, sent them and a ton of these came back over time.

I sent 2 TXes, resulting in all these alerts and also the failed TX from other people (using the same private key I assume) coming in.

**Comment by dgenr8** [comment]
So that's what mom meant when she said there's no such thing as a free lunch ;)

**Comment by zander** [comment]
I actually have been hit by a similar issue quite some time ago.  I'll take a look.
