### ISSUE TITLE
0.11B debian build autostarts, but not documented that way

### ISSUE THREAD

**Issue by Beanow** [bitcoinxt/bitcoinxt#68]
Near the bottom of https://bitcoinxt.software/apt.html
```
Note that the server binary is named "bitcoinxt" in this package,
not bitcoind. There are no init scripts or other such things installed,
so please be aware that the node will not be started, and if you do
an apt-get upgrade, you will have to restart the server yourself for
the update to take effect.
```

But since 0.11B it actually does auto-start when you've got systemd.
In fact it even auto-restarts. Which is confusing when you're not expecting it.

I'm not sure what the intended behaviour is, but either should be updated to be consistent.

**Comment by zander** [comment]
Thanks, this is outdated info, we made it autostart on systemd systems. I created a merge request for the website.

**Comment by Beanow** [comment]
@zander if it is the intended behaviour, I think it should do this for other configurations than systemd as well. Like SysV style init.d, etc. The [current postinst](https://github.com/bitcoinxt/bitcoinxt/blob/0.11B/contrib/gitian-debian/build.sh#L92) checks for systemd only and outputs a message otherwise.

**Comment by fraggle222** [comment]
Personally I don't like this new behavior. I don't think it should autostart on install. 

Anyone upgrading from .11A using apt-get will have problems: daemon autostarts and can't be killed (systemd is fairly new to Ubuntu as the standard , files in different directories (including where all the blocks are stored, bitcoin.conf, etc.).

Autostarting **by default** almost seems sneaky and bitcoin (not to mention bitcoinxt) needs to be very careful about that. People who decide to run nodes need to have a measure of control.

Clear instructions on how to add bitcoinxt daemon to systemd (with explanation on how to specify where files will be stored, conf directory, etc) would be enough.

Stopping bitcoinxd using bitcoinxt-cli stop did not work.

**Comment by zander** [comment]
@Beanow we currently only have expertise on systemd, which is by far the most used init system in use today on Debian systems.
If you feel strongly about other init systems and feel there are people that benefit from support, please feel free to pick up that maintainer task.  We always welcome contributors :)

@fraggle222 any service that is managed by the system (systemd in this case) needs to be configured using the system tools.  A quick google gave me a nice tutorial you may enjoy: https://www.linux.com/learn/tutorials/527639-managing-services-on-linux-with-systemd

BitcoinXT is, by its very nature, something that should run in the background. Just like a webserver or really any infrastructure.  It naturally autostarts.  If you only start it when you need it, say, once a week, you will have a very bad time.

**Comment by Beanow** [comment]
You mean debian based desktops. Systemd was not introduced to debian servers till v8 (jessie). Before then everything ran from init.d. With service <x> start. And a fair amount of server admins dislike the change, switching back. So I think supporting that would benefit many.

Before looking at adding this though, feedback is trickling in that it shouldn't autostart. Would like a conclusive answer on whether it should from Mike/Gavin.

TomZ <notifications@github.com> schreef op 11 september 2015 13:15:15 CEST:

**Comment by zander** [comment]
Yes, you are right. Debian desktops. If there is such a need and you can add the support for another init system in the same deb file, that would be wonderful.

I'm not sure if the main guys will be reading mail much this week (or the next) so you might wait a long time.
@stevemyers may have a say since he added the systemd support.  But I'm pretty sure we want it to autostart.

**Comment by Beanow** [comment]
Also worth considering, making it interactive. "Register bitcoinxt to automatically start as a service? [Y/n]" "Start bitcoinxt daemon now? [Y/n]" sort of thing. Many deb packages do this for basic (re-)configuration.

Perhaps I'll have a go at making a PR for these things, but want to make sure it's desirable and won't get rejected for that.

TomZ <notifications@github.com> schreef op 11 september 2015 13:40:10 CEST:

**Comment by fraggle222** [comment]
Generally 'apt-get install' should not start any process that is potentially CPU, memory or disk intensive (without asking, see above). Compare to say "apache" which does not start eating up 45GB when it runs the first time and will only consume CPU, I/O if the website already has a ton of traffic. Same for something like Postfix or sshd, or many other 'services'. 

Also is there any way to pass in to 'apt-get' a preferred directory for bitcoin.conf and where to store all the data?

**Comment by zander** [comment]
I personally reject the idea that installing packages per the instructions (adding key, adding source, installing) has to be made such that people that don't know what they are installing don't get hurt.

BitcoinXT is primarily a node on the network of Bitcoin. For that it has to run automatically.

**Comment by stevemyers** [comment]
I don't mind changing the deb packaging script to ask before automatically enabling and starting the bitcoinxtd.service.  I can see that some people may want to manually change the bitcoin.conf file before starting the daemon.

**Comment by Beanow** [comment]
On 11/09/15 19:42, Steve Myers wrote:
>
> I don't mind changing the deb packaging script to ask before automatically enabling and starting the bitcoinxtd.service. I can see that some people may want to manually change the bitcoin.conf file before starting the daemon.
>
Exactly that argument was going to be my point.
Instantly starting with resource hogging, also not the best thing to do, but more importantly I think you would want to change some config values.

**Comment by stevemyers** [comment]
I would make the default answer to the "automatically start daemon?" question Y though since as zander said the primary purpose of this package is for deploying and starting the daemon.

**Comment by stevemyers** [comment]
@zander thanks for updating the docs.

**Comment by stevemyers** [comment]
I created pull request #71 to ask the user if they want to autostart the ```bitcoinxtd``` daemon during installation of the debian package.  If the system being installed on doesn't have ```systemctl``` then no autostart is done (as before) and no question is asked.  

@Beanow please take a look and let me know what you think.  
@zander if this change goes in I think we should update the web page again too. Thanks

**Comment by mikehearn** [comment]
I'm personally fine with auto-starting, there's no point in installing a program if you aren't going to run it. I don't find it to be sneaky, it's normal for server packages to do that. 

However I am happy to delegate to Steve on Debian/packaging matters, so I merged his PR to use debconf to ask the user.

> Stopping bitcoinxtd using bitcoinxt-cli stop did not work

This is a different issue. SystemD doesn't know that the exit was user requested. Perhaps it has some way to handle restarting only when the exit code != 0.

Alternatively XT could know when its lifecycle is being managed externally and communicate that to the bitcoin-cli command, so users get an error that tells them how to shut it down properly.
