### ISSUE TITLE
Build / git issues with 0.10.1

### ISSUE THREAD

**Issue by gurnec** [bitcoinxt/bitcoinxt#7]
While trying to reproduce the 0.10.1 gitian build, I've run into a few minor but confusing issues.

The first is that the "0.10.1" tag points to some old commit. A somewhat related issue is that there exists a branch and a tag both named "0.10.1" which is somewhat confusing with git, and extremely confusing on GitHub.

By somewhat confusing with git, I simply mean that if I ask gbuild to build 0.10.1, git selects the old 0.10.1 tag instead of what I wanted (the head of the 0.10.1 branch).

By extremely confusing on GitHub, I mean:
 * If you attempt to select the tag named "0.10.1", you end up viewing the head of the 0.10.1 branch instead (this appears to be a GitHub bug).
 * If you go to the 0.10.1 *release* page:
    * the release is dated Dec 28, 2014 (the date of the commit the old tag points to; the most recent release is listed as 0.10.0 final)
    * the branch link (upper left) links to the current 0.10.1 branch
    * the commit link links to the old 0.10.1 tagged commit
    * the binaries are the ones that were recently uploaded presumably from the current 0.10.1 branch
    * the source tarball is from (I believe) the old 0.10.1 commit

In short, really confusing....

The second issue was just a question: which commit is the (new) 0.10.1 release? Is it 7dd901c as listed in the [gitian sigs](https://github.com/bitcoinxt/gitian.sigs/blob/master/linux/0.10.1/mike%40plan99.net/bitcoin-linux-0.10-build.assert#L11)? That commit does not appear to be connected to any branches:

    $ git clone https://github.com/bitcoinxt/bitcoinxt.git
    Cloning into 'bitcoinxt'...
    remote: Counting objects: 44988, done.
    remote: Total 44988 (delta 0), reused 0 (delta 0), pack-reused 44988
    Receiving objects: 100% (44988/44988), 32.94 MiB | 6.66 MiB/s, done.
    Resolving deltas: 100% (33751/33751), done.
    Checking connectivity... done.
    $ git checkout 7dd901c7f6571afdfeda260f5bc2990cab3dcb7a
    fatal: reference is not a tree: 7dd901c7f6571afdfeda260f5bc2990cab3dcb7a

Was that commit amended into 2a1ebf1 perhaps?

**Comment by mikehearn** [comment]
Yes, I noticed these problems as well.

I plan to take some time in the next few days to come up with a different workflow to try and avoid hitting github/gbuild issues like this.

The commit was amended to update the README to point to the right download link. It's a fudge because there's no website. Obviously once there's a website there won't be any need to do that anymore.

In short: yes I know this is kind of a mess. The branches/tags need to be fully separated from the ones upstream uses.

**Comment by mikehearn** [comment]
The 0.10.2A release should be easier to reproduce. I gave it a tag that doesn't have the same name as the branch this time, so now things are sorted out.

**Comment by gurnec** [comment]
FYI I had no trouble doing a gitian build of 0.10.2A and verifying the sigs, thanks for your efforts!

**Comment by mikehearn** [comment]
Great! If you want to contribute your sigs to the repo, that'd be appreciated!
