### ISSUE TITLE
build broken - net.cpp - error `CLIENT_VERSION_XT_SUBVER` not declared

### ISSUE THREAD

**Issue by gubatron** [bitcoinxt/bitcoinxt#70]
Just did a pull, tried to make and got this error. This probably shouldn't happen.
(I had built before, maybe about two weeks ago, no problems)
```
net.cpp: In member function ‘void CNode::PushVersion()’:
net.cpp:438:103: error: ‘CLIENT_VERSION_XT_SUBVER’ was not declared in this scope
                 nLocalHostNonce, FormatSubVersion(CLIENT_NAME, CLIENT_VERSION, std::vector<string>(), CLIENT_VERSION_XT_SUBVER), nBestHeight, true);
```

tried doing a `make clean`, `make`, but still nothing, guess I'll try to run `./configure` again.

**Comment by gubatron** [comment]
nothing after cleaning and reconfiguring, the `CLIENT_VERSION_XT_SUBVER` definition will not be defined inside `bitcoin-config.h`.

I'm configuring my build with a switch to disable building the wallet, perhaps that has something to do with this. (`./configure --disable--wallet`)

I'm a noob when it comes to configure.ac and autoheader, any clue what could be the cause?

On my Makefile I see it's defined as: `CLIENT_VERSION_XT_SUBVER = B`

For now I've just declared the macro manually in `bitcoin-config.h` to be able to build
`#define CLIENT_VERSION_XT_SUBVER "B"`

**Comment by dgenr8** [comment]
Run autogen.sh

**Comment by gubatron** [comment]
thanks!
