### ISSUE TITLE
Checksums for sources do not match

### ISSUE THREAD

**Issue by jrruethe** [bitcoinxt/bitcoinxt#77]
Downloading the source archive from this link:
https://github.com/bitcoinxt/bitcoinxt/releases
https://github.com/bitcoinxt/bitcoinxt/archive/v0.11B.tar.gz
Gives me a sha256sum of:
f9fa35a0996d8b8b4eb20d77087b4463d84dc907124b73250cd82e81eed38139  bitcoinxt-0.11B.tar.gz

Whereas, the signed Gitian assert files claim the source sha256sum should be:
https://github.com/bitcoinxt/gitian.sigs/blob/master/0.11B-linux/gavinandresen/bitcoin-linux-0.11-build.assert
4af0c59de2c5d46ca250cb8b95877eae98298abfa52e9e90c71f7f785219aa6e  src/bitcoin-xt-0.11.0-B.tar.gz

I suspect this is because the source archive is being generated by Github, which is somehow different from the sources being used by Gitian. If possible, I would like to get the source tar.gz that has been signed.

Thank you!

**Comment by mikehearn** [comment]
If you want to reproduce the build yourself, you need to use gitian. You can't just grab the same source tarball, compile it and get the same build outputs. And if you do that (build the 0.11B branch) then you should get the identical source tarball out. Does that help?

**Comment by jrruethe** [comment]
I'll look into gitian, I'm not super familiar with it. However, I'm not trying to reproduce the same build outputs, I'm trying to make sure I'm using the same build inputs. In other words, I want to be using the same source tarball that you guys used and signed.

Thanks for your response!
