### ISSUE TITLE
Reported version string

### ISSUE THREAD

**Issue by pryds** [bitcoinxt/bitcoinxt#8]
According to getaddr.bitnodes.io, Bitcoin XT reports its version string as "/Satoshi:0.10.1/" -- i.e. the same as Bitcoin Core. Is this intentional?
Bitcoin XT version v0.10.1.0-7dd901c (64-bit)

**Comment by mikehearn** [comment]
No, and I fixed it at some point but I must have accidentally reverted to an earlier patch during a rebase. Hence my comments about finding a better workflow. I will fix this soon.

**Comment by vuego** [comment]
To me it looks like bitcoinxt 0.10.1 from 28 dec 2014 reports its version as "/Satoshi:0.10.1/" and 0.10.0 final from 13 feb 2015 reports as version "/Bitcoin XT:0.10.0/".

**Comment by mikehearn** [comment]
This was fixed in 0.10.2A
