### ISSUE TITLE
Enable bountysource contribution.

### ISSUE THREAD

**Issue by F483** [bitcoinxt/bitcoinxt#9]
Given the recent block size issues and [Gavin's message](http://sourceforge.net/p/bitcoin/mailman/message/34155307/), I would like to show support by contributing some funds to this project.

Currently contributions are disabled and it would be nice if this changed.

https://www.bountysource.com/teams/bitcoinxt

**Comment by mikehearn** [comment]
Interesting idea, thanks. I think if we were to raise funds for XT work it'd be via Lighthouse though, as that's more Bitcoin native. I'll reconsider this idea if we find the workload is higher than expected and the amounts needed can't be raised in some other way. Thanks again!
